"""
Custom — user supplies their own Dockerfile.

We scaffold a folder with a placeholder Dockerfile, a sample flag.txt
the user can copy/move/edit, and a README explaining what to change.
"""

from __future__ import annotations

from pathlib import Path

from instances.models import Instance
from vulnerabilities import Vulnerability
from generators._common import (
    ensure_dir, write_text, realize_flag, write_run_scripts,
)


_PLACEHOLDER_DOCKERFILE = '''# Auto-generated by CTFToyBox — replace with your own challenge.
#
# Tips:
#  - Put any source files alongside this Dockerfile and COPY them in.
#  - Expose the port your service listens on (matches the host mapping
#    you chose in the deploy wizard).
#  - Keep the final image small — alpine/-slim/-bookworm-slim are good.
#
# A sample flag.txt has been generated for you. Move/edit/embed it
# however your challenge needs.

FROM alpine:3.19

WORKDIR /app
COPY flag.txt /flag.txt

# COPY your-source-here .

# EXPOSE <port>
CMD ["/bin/sh", "-c", "echo 'Replace this Dockerfile with your challenge.'; tail -f /dev/null"]
'''

_README = '''# {name}

**Category:** Custom
**Difficulty:** user-defined

## What's here
A scaffold for your own CTF challenge. The wizard wrote:
- `Dockerfile`        — placeholder; replace with your real challenge
- `flag.txt`          — sample flag; embed/move/transform as your challenge needs
- `build.sh / .bat`   — runs `docker build`
- `run.sh   / .bat`   — runs `docker run` with the resource limits you chose
- `stop.sh  / .bat`   — stops + removes the container

Drop your source files into this folder, edit the Dockerfile to COPY and
build them, then run the build/run scripts as usual.

## Resources you allocated
- CPU:    {cpu} cores
- Memory: {mem} MB
- Ports:  {ports}

## Generated flag
`{flag}`
'''


def generate(instance: Instance, vuln: Vulnerability) -> None:
    folder = ensure_dir(Path(instance.working_dir))

    flag = realize_flag(vuln.flag_template, challenge_slug=instance.name)

    write_text(folder / "Dockerfile", _PLACEHOLDER_DOCKERFILE)
    write_text(folder / "flag.txt",   flag + "\n")

    if instance.resources.port_mappings:
        ports_str = ", ".join(
            f"{h}→{c}" for h, c in instance.resources.port_mappings
        )
    else:
        ports_str = "(none)"

    write_text(folder / "README.md", _README.format(
        name=instance.name,
        cpu=instance.resources.cpu_cores,
        mem=instance.resources.memory_mb,
        ports=ports_str,
        flag=flag,
    ))

    write_run_scripts(
        folder,
        image_tag=f"ctfmgr/{instance.id}",
        container_name=f"ctfmgr_{instance.id}",
        instance=instance,
    )