"""
Forensics — flag hidden in image metadata + appended after EOI.

The container builds a JPEG at first run:
  - a tiny solid-color JPEG written byte-by-byte (no Python imaging deps)
  - the flag stored both in an EXIF-style COM (comment) marker and
    appended after the JPEG end-of-image bytes

Players use `strings`, `exiftool`, or a hex editor on the produced file.
"""

from __future__ import annotations

from pathlib import Path

from instances.models import Instance
from vulnerabilities import Vulnerability
from generators._common import (
    ensure_dir, write_text, realize_flag, write_run_scripts,
)


_BUILDER_PY = '''"""Auto-generated by CTFToyBox.
Generates challenge.jpg with a flag hidden in (a) a JPEG COM marker and
(b) bytes appended after the End-Of-Image marker.
"""
import os, struct

FLAG = os.environ.get("CHALL_FLAG", "flag{{missing}}").encode()

# Minimal valid JPEG: SOI + APP0 (JFIF) + DQT + SOF0 + DHT + SOS + 1 byte data + EOI.
# We don't need a real image — `strings` and `exiftool` only care about markers.
JPEG_BASE = bytes.fromhex(
    "ffd8ffe000104a46494600010100000100010000"           # SOI + APP0 (JFIF)
    "ffdb0043000806060706050807070709090808"             # DQT (truncated luminance)
    "0a0c140d0c0b0b0c1912130f141d1a1f1e1d1a1c1c20242e27"
    "20222c231c1c2837292c30313434341f27393d38323c2e333432"
    "ffc0000b08000100010101110000"                        # SOF0 1x1 grayscale
    "ffc4001f0000010501010101010100000000000000000102030405060708090a0b" # DHT
    "ffda0008010100003f00"                                # SOS
    "37"                                                  # 1 byte image data
    "ffd9"                                                # EOI
)

def jpeg_with_comment(base: bytes, comment: bytes) -> bytes:
    # COM marker = 0xFFFE, then 2-byte big-endian length (incl length bytes), then data.
    payload = comment
    com = b"\\xff\\xfe" + struct.pack(">H", 2 + len(payload)) + payload
    # Insert COM right after SOI (first 2 bytes), before APP0.
    return base[:2] + com + base[2:]

def main():
    out = jpeg_with_comment(JPEG_BASE, b"Hidden in plain sight: " + FLAG)
    # And append after EOI for good measure (often spotted via `strings`).
    out += b"\\n--appendix--\\n" + FLAG + b"\\n"
    with open("/out/challenge.jpg", "wb") as f:
        f.write(out)
    print("Wrote /out/challenge.jpg ({{}} bytes)".format(len(out)))

if __name__ == "__main__":
    main()
'''

_DOCKERFILE = '''# Auto-generated by CTFToyBox
FROM python:3.12-slim

WORKDIR /app
COPY make_challenge.py .

RUN mkdir /out
ENV CHALL_FLAG="{flag}"
RUN python /app/make_challenge.py

# The challenge artifact lives at /out/challenge.jpg.
# Players retrieve it via:  docker cp <container>:/out/challenge.jpg .
CMD ["/bin/sh", "-c", "echo 'Image at /out/challenge.jpg — copy with: docker cp <container>:/out/challenge.jpg .'; tail -f /dev/null"]
'''

_README = '''# {name}

**Category:** Forensics
**Template:** {template_name}
**Difficulty:** easy

## How it works
A small Python script generates a JPEG with the flag hidden in two places:
- inside a JPEG COM (comment) marker — visible to `exiftool` / hex editor
- appended after the EOI bytes — visible to plain `strings`

## Build & run
```
./build.sh && ./run.sh
```

Grab the artifact:
```
docker cp {container_name}:/out/challenge.jpg .
strings challenge.jpg | grep -i flag
```

## Solver hint (for organizers)
Flag: `{flag}`
'''


def generate(instance: Instance, vuln: Vulnerability) -> None:
    folder = ensure_dir(Path(instance.working_dir))

    flag = realize_flag(vuln.flag_template)

    write_text(folder / "make_challenge.py", _BUILDER_PY)
    write_text(folder / "Dockerfile",        _DOCKERFILE.format(flag=flag))
    write_text(folder / "README.md",         _README.format(
        name=instance.name,
        template_name=vuln.name,
        container_name=f"ctfmgr_{instance.id}",
        flag=flag,
    ))

    write_run_scripts(
        folder,
        image_tag=f"ctfmgr/{instance.id}",
        container_name=f"ctfmgr_{instance.id}",
        instance=instance,
    )