"""
Reverse Engineering — hardcoded password checker.

Builds a small C program with a `strcmp`-based password check and the
flag baked in. The container's `CMD` just emits the binary path so the
player can copy it out (e.g. via `docker cp`).
"""

from __future__ import annotations

from pathlib import Path

from instances.models import Instance
from vulnerabilities import Vulnerability
from generators._common import (
    ensure_dir, write_text, realize_flag, write_run_scripts,
)


_C_SOURCE = '''/* Auto-generated by CTF Manager.
 * Beginner crackme: enter the password baked into the binary.
 */
#include <stdio.h>
#include <string.h>

static const char password[] = "{password}";
static const char flag[]     = "{flag}";

int main(void) {{
    char input[64];

    printf("Enter the password: ");
    if (!fgets(input, sizeof(input), stdin)) {{
        return 1;
    }}
    /* trim trailing newline */
    input[strcspn(input, "\\r\\n")] = 0;

    if (strcmp(input, password) == 0) {{
        printf("Correct! %s\\n", flag);
        return 0;
    }}
    printf("Nope.\\n");
    return 1;
}}
'''

_DOCKERFILE = '''# Auto-generated by CTF Manager
FROM gcc:12-bookworm AS builder
WORKDIR /build
COPY chall.c .
RUN gcc -O0 -no-pie -fno-stack-protector -o chall chall.c

FROM debian:bookworm-slim
COPY --from=builder /build/chall /chall
CMD ["/bin/sh", "-c", "echo 'Binary at /chall — copy it out with: docker cp <container>:/chall .'; tail -f /dev/null"]
'''

_README = '''# {name}

**Category:** Reverse Engineering
**Template:** {template_name}
**Difficulty:** easy

## How it works
A C program with a hardcoded password and a flag. The build copies the
compiled binary into a slim runtime image. Players reverse the binary to
recover the password — `strings`, `ltrace`, or any decompiler will do.

## Build & run
```
./build.sh && ./run.sh    # macOS / Linux
build.bat  &  run.bat     # Windows
```

Then grab the binary out of the container:
```
docker cp {container_name}:/chall ./chall
```

## Solver hint (for organizers)
Password: `{password}`
Flag:     `{flag}`
'''


def generate(instance: Instance, vuln: Vulnerability) -> None:
    folder = ensure_dir(Path(instance.working_dir))

    # The "password" is just a memorable hex tag — distinctive enough that
    # a player who runs `strings` will spot it.
    password = f"reveng_{instance.id.split('-')[-1]}"
    flag     = realize_flag(vuln.flag_template)

    write_text(folder / "chall.c",    _C_SOURCE.format(password=password, flag=flag))
    write_text(folder / "Dockerfile", _DOCKERFILE)
    write_text(folder / "README.md",  _README.format(
        name=instance.name,
        template_name=vuln.name,
        container_name=f"ctfmgr_{instance.id}",
        password=password,
        flag=flag,
    ))

    write_run_scripts(
        folder,
        image_tag=f"ctfmgr/{instance.id}",
        container_name=f"ctfmgr_{instance.id}",
        instance=instance,
    )