"""
Top-level dispatch: take a template + chosen services, write a complete
folder of scripts + docs to disk.

Bundle contents:
  setup.{ps1,sh}        — the master setup script
  README.md             — how to run it + safety warnings
  VULNERABILITIES.md    — full inventory of vulns + defenses + services
  rollback.{ps1,sh}     — best-effort cleanup script (not a full uninstaller)
"""

from __future__ import annotations

import os
from pathlib import Path

from system_templates.registry import SystemTemplate, TargetOS
from system_templates.services import LiveService, get_service
from system_templates.generators import windows as gen_windows
from system_templates.generators import linux   as gen_linux


class GenerationError(Exception):
    """Raised when bundle generation fails."""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def _write_text(path: Path, content: str, *, executable: bool = False):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    if executable:
        try:
            os.chmod(path, 0o755)
        except OSError:
            pass  # Windows — ignored.


# ---------------------------------------------------------------------------
# README + VULNERABILITIES.md generators
# ---------------------------------------------------------------------------

def _build_readme(template: SystemTemplate, services: list[LiveService]) -> str:
    is_windows = template.target_os is TargetOS.WINDOWS_11
    setup_cmd = (
        "powershell -ExecutionPolicy Bypass -File .\\setup.ps1"
        if is_windows else
        "sudo bash ./setup.sh"
    )
    rollback_cmd = (
        "powershell -ExecutionPolicy Bypass -File .\\rollback.ps1"
        if is_windows else
        "sudo bash ./rollback.sh"
    )

    svc_list = (
        "\n".join(f"- {s.name} — {s.summary}" for s in services)
        if services else "_(none chosen)_"
    )

    return f"""# {template.name}

**Target OS:** {template.target_os.display_name}
**Difficulty tier:** {template.tier.display_name}

{template.description}

---

## ⚠ Safety

Running the setup script will **deliberately weaken** the host it runs on.
Run **only** on a disposable VM, sandboxed environment, or dedicated lab
machine. Snapshot before, snapshot after.

There is no full uninstaller. `rollback.{('ps1' if is_windows else 'sh')}` does
best-effort cleanup of the artifacts this template creates, but it cannot
fully revert system-policy or audit changes.

## Run

```
{setup_cmd}
```

After it finishes, see `VULNERABILITIES.md` for the full attack surface
inventory and how each vuln is intended to be exploited.

## Rollback (best-effort)

```
{rollback_cmd}
```

## Live services included

{svc_list}
"""


def _build_vulnerabilities_md(template: SystemTemplate, services: list[LiveService]) -> str:
    lines: list[str] = [
        f"# Vulnerabilities & Defenses — {template.name}",
        "",
        f"**Target OS:** {template.target_os.display_name}  ",
        f"**Difficulty tier:** {template.tier.display_name}",
        "",
        "Generated by CTFToyBox. Use this as the answer key when running the lab.",
        "",
        "---",
        "",
        "## Vulnerabilities planted",
        "",
    ]

    if template.vulnerabilities:
        for i, v in enumerate(template.vulnerabilities, 1):
            cwe = f"  \n  *Reference:* {v.cwe}" if v.cwe else ""
            lines.append(f"{i}. **{v.name}**  ")
            lines.append(f"   {v.detail}{cwe}")
            lines.append("")
    else:
        lines.append("_(none — this template ships with no template-level vulns; "
                     "anything below comes from the chosen services.)_")
        lines.append("")

    if services:
        lines.append("### Vulnerabilities added by chosen services")
        lines.append("")
        for svc in services:
            if not svc.vulnerabilities:
                continue
            lines.append(f"**{svc.name}**")
            for v in svc.vulnerabilities:
                cwe = f" *({v.cwe})*" if v.cwe else ""
                lines.append(f"- {v.name}{cwe} — {v.detail}")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Defenses enabled")
    lines.append("")
    if template.defenses:
        for d in template.defenses:
            lines.append(f"- **{d.name}** — {d.detail}")
    else:
        lines.append("_(none — this is an Easy-tier template; only OS defaults are in place.)_")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Live services running")
    lines.append("")
    if services:
        for s in services:
            lines.append(f"- **{s.name}** — {s.summary}")
    else:
        lines.append("_(none chosen.)_")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Rollback scripts — best-effort, scoped to artifacts we know we created
# ---------------------------------------------------------------------------

_WINDOWS_ROLLBACK = r"""# Best-effort rollback — does NOT fully revert policy/audit changes.
$ErrorActionPreference = 'SilentlyContinue'

Write-Host '[*] Removing local user jdoe (if present)...'
Remove-LocalUser -Name 'jdoe'

Write-Host '[*] Removing SMB shares...'
foreach ($n in 'Files','LabShare') { Remove-SmbShare -Name $n -Force }

Write-Host '[*] Removing custom service CTFLabSvc and folder...'
sc.exe stop   CTFLabSvc
sc.exe delete CTFLabSvc
Remove-Item -Recurse -Force 'C:\Program Files\CTFLab'

Write-Host '[*] Removing scheduled task and ProgramData folder...'
schtasks /Delete /TN CTFLabHousekeep /F
Remove-Item -Recurse -Force 'C:\ProgramData\CTFLab'

Write-Host '[*] Clearing Winlogon AutoAdmin remnants...'
$wl = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
Remove-ItemProperty -Path $wl -Name DefaultPassword
Remove-ItemProperty -Path $wl -Name DefaultUserName
Remove-ItemProperty -Path $wl -Name AutoAdminLogon

Write-Host '[*] Removing planted lab files / FTP root / SMB share dir...'
Remove-Item -Recurse -Force 'C:\Files'
Remove-Item -Recurse -Force 'C:\Lab'
Remove-Item -Recurse -Force 'C:\ftp'

Write-Host 'Rollback complete (best-effort). Audit policy and Defender state were not changed.'
"""

_LINUX_ROLLBACK = r"""#!/usr/bin/env bash
# Best-effort rollback — does NOT fully revert auditd / AppArmor / UFW state.
set +e

echo '[*] Removing user jdoe...'
userdel -r jdoe 2>/dev/null

echo '[*] Removing planted artifacts...'
rm -rf /srv/backup /srv/samba/public /srv/ftp/anon
rm -rf /opt/app   /opt/ctflab        /var/log/ctflab-heartbeat.log
rm -f  /etc/sudoers.d/99-ctfmgr-nmap
rm -f  /etc/cron.d/ctflab-housekeep
rm -f  /usr/local/bin/ctflab-backup
rm -rf /tmp/ctflab-backup-input /tmp/ctflab-backup.tar

echo '[*] Removing share entry from smb.conf (if present)...'
sed -i '/\[public\]/,/^$/d' /etc/samba/smb.conf 2>/dev/null
systemctl restart smbd 2>/dev/null

echo '[*] Removing webroot lab files...'
rm -rf /var/www/html/.git /var/www/html/backup /var/www/html/share
rm -f  /var/www/html/config.php~

echo '[*] Removing fail2ban / auditd rules we added (services left installed)...'
rm -f /etc/fail2ban/jail.d/ctflab.local
rm -f /etc/audit/rules.d/ctflab.rules
systemctl restart fail2ban 2>/dev/null
augenrules --load >/dev/null 2>&1 || true

echo 'Rollback complete (best-effort).'
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_template_bundle(
    template: SystemTemplate,
    service_ids: list[str],
    output_dir: str,
) -> Path:
    """
    Write all generated files for a system template into `output_dir`.
    Returns the resolved Path.
    """
    folder = _ensure_dir(Path(output_dir))

    # Resolve services (and quietly drop any that don't apply to this OS)
    services: list[LiveService] = []
    for sid in service_ids:
        s = get_service(sid)
        if s is None:
            continue
        if template.target_os not in s.supported_os:
            continue
        services.append(s)

    is_windows = template.target_os is TargetOS.WINDOWS_11
    try:
        if is_windows:
            setup_text = gen_windows.build_setup_script(template, services)
            _write_text(folder / "setup.ps1", setup_text)
            _write_text(folder / "rollback.ps1", _WINDOWS_ROLLBACK)
        else:
            setup_text = gen_linux.build_setup_script(template, services)
            _write_text(folder / "setup.sh",    setup_text,    executable=True)
            _write_text(folder / "rollback.sh", _LINUX_ROLLBACK, executable=True)

        _write_text(folder / "README.md",
                    _build_readme(template, services))
        _write_text(folder / "VULNERABILITIES.md",
                    _build_vulnerabilities_md(template, services))
    except OSError as e:
        raise GenerationError(f"Filesystem error: {e}") from e

    return folder